{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0921639",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask, Response, render_template\n",
    "import cv2\n",
    "\n",
    "\n",
    "app = Flask(__name__)\n",
    "cap = cv2.VideoCapture(0)\n",
    "@app.route('/')\n",
    "def About Us():\n",
    "    return  render_template('About Us.html')\n",
    "\n",
    "def generate_frames():\n",
    "    while True:\n",
    "        success, frame = cap.read()\n",
    "        imgOutput=frame.copy()\n",
    "        yield (b'--frame\\r\\n'\n",
    "               b'Content-Type: image/jpeg\\r\\n\\r\\n' + imgOutput + b'\\r\\n')\n",
    "@app.route('/predict',methods=['POST','GET'])\n",
    "from PyQt5.QtWidgets import QApplication\n",
    "from PyQt5.QtWidgets import QWidget\n",
    "\n",
    "from PyQt5.QtGui import QImage\n",
    "from PyQt5.QtGui import QPixmap\n",
    "from PyQt5.QtCore import QTimer\n",
    "\n",
    "\n",
    "from PyQt5 import QtCore, QtGui, QtWidgets\n",
    "\n",
    "import tensorflow.keras as tf\n",
    "import cv2\n",
    "import numpy as np\n",
    "import operator\n",
    "import sys, os\n",
    "import enchant\n",
    "from string import ascii_uppercase\n",
    "import turtle\n",
    "import time\n",
    "from multiprocessing import Process\n",
    "from PyQt5 import QtCore, QtGui, QtWidgets\n",
    "import pyttsx3\n",
    "from PyQt5 import QtCore, QtGui, QtWidgets\n",
    "from PyQt5.QtWidgets import QMainWindow, QAction, qApp, QApplication\n",
    "\n",
    "\n",
    "engine = pyttsx3.init()\n",
    "def loader():\n",
    "\n",
    "    turtle.setup(900, 500)\n",
    "    t = turtle.Turtle()\n",
    "    screen = turtle.Screen()\n",
    "    screen.title(\"Sign To Text\")\n",
    "    screen.bgpic(\"t.png\")\n",
    "    t.hideturtle()\n",
    "\n",
    "    t.penup()\n",
    "    t.goto(0, 110)\n",
    "    t.pendown()\n",
    "    t.pencolor(\"black\")\n",
    "    t.write(\"Sign To Text\", move='true', align=\"center\", font=(\"Georgia\", 50))\n",
    "    t.penup()\n",
    "\n",
    "    t.goto(-20, 80)\n",
    "    t.pendown()\n",
    "    t.write(\"For Deaf & Dumbs\", align=\"left\", font=(\"georgia\", 15, \"normal\", 'italic'))\n",
    "    t.penup()\n",
    "    t.goto(-20, 60)\n",
    "    t.pendown()\n",
    "\n",
    "    t.penup()\n",
    "    t.goto(-207, -130)\n",
    "    t.pendown()\n",
    "    t.pencolor(\"white\")\n",
    "    t.write(\"Initializing .......\", align='right', font=(\"Ariel\", 13, 'normal', 'italic'))\n",
    "\n",
    "\n",
    "\n",
    "    t.pensize(3)\n",
    "    t.penup()\n",
    "    t.goto(-300, -100)\n",
    "    t.pendown()\n",
    "\n",
    "    t.forward(200)\n",
    "    time.sleep(9)\n",
    "    t.forward(150)\n",
    "    time.sleep(9)\n",
    "    t.forward(200)\n",
    "\n",
    "    time.sleep(9)\n",
    "    t.forward(100)\n",
    "    time.sleep(9)\n",
    "    t.forward(90)\n",
    "    time.sleep(9)\n",
    "    turtle.bye()\n",
    "\n",
    "class Ui_MainWindow(object):\n",
    "    def setupUi(self, MainWindow):\n",
    "        MainWindow.setObjectName(\"MainWindow\")\n",
    "        MainWindow.resize(801, 626)\n",
    "        palette = QtGui.QPalette()\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)\n",
    "        MainWindow.setPalette(palette)\n",
    "        font = QtGui.QFont()\n",
    "        font.setPointSize(8)\n",
    "        MainWindow.setFont(font)\n",
    "        MainWindow.setAutoFillBackground(True)\n",
    "        self.centralwidget = QtWidgets.QWidget(MainWindow)\n",
    "        self.centralwidget.setObjectName(\"centralwidget\")\n",
    "        self.Heading = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.Heading.setGeometry(QtCore.QRect(0, 0, 801, 41))\n",
    "        palette = QtGui.QPalette()\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(213, 234, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(149, 202, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(56, 113, 170))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(170, 212, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(213, 234, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(149, 202, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(56, 113, 170))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(170, 212, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(213, 234, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(149, 202, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(56, 113, 170))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)\n",
    "        self.Heading.setPalette(palette)\n",
    "        font = QtGui.QFont()\n",
    "        font.setFamily(\"Baskerville Old Face\")\n",
    "        self.Heading.setFont(font)\n",
    "        self.Heading.setAutoFillBackground(True)\n",
    "        self.Heading.setObjectName(\"Heading\")\n",
    "        self.Img = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.Img.setGeometry(QtCore.QRect(400, 70, 381, 281))\n",
    "        self.Img.setText(\"\")\n",
    "        self.Img.setPixmap(QtGui.QPixmap(\"signs.png\"))\n",
    "        self.Img.setScaledContents(True)\n",
    "        self.Img.setObjectName(\"Img\")\n",
    "        self.character = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.character.setGeometry(QtCore.QRect(20, 340, 101, 31))\n",
    "        self.character.setObjectName(\"character\")\n",
    "        self.word = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.word.setGeometry(QtCore.QRect(10, 380, 101, 31))\n",
    "        self.word.setObjectName(\"word\")\n",
    "        self.sentence = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.sentence.setGeometry(QtCore.QRect(20, 420, 101, 31))\n",
    "        self.sentence.setObjectName(\"sentence\")\n",
    "        self.ch = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.ch.setGeometry(QtCore.QRect(130, 340, 101, 31))\n",
    "        palette = QtGui.QPalette()\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)\n",
    "        self.ch.setPalette(palette)\n",
    "        font = QtGui.QFont()\n",
    "        font.setFamily(\"Copperplate Gothic Light\")\n",
    "        font.setPointSize(12)\n",
    "        self.ch.setFont(font)\n",
    "        self.ch.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))\n",
    "        self.ch.setAutoFillBackground(True)\n",
    "        self.ch.setObjectName(\"ch\")\n",
    "        self.word1 = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.word1.setGeometry(QtCore.QRect(120, 380, 181, 31))\n",
    "        font = QtGui.QFont()\n",
    "        font.setFamily(\"Copperplate Gothic Light\")\n",
    "        font.setPointSize(12)\n",
    "        self.word1.setFont(font)\n",
    "        self.word1.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))\n",
    "        self.word1.setAutoFillBackground(True)\n",
    "        self.word1.setObjectName(\"word1\")\n",
    "        self.sentence1 = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.sentence1.setGeometry(QtCore.QRect(120, 420, 601, 31))\n",
    "        font = QtGui.QFont()\n",
    "        font.setFamily(\"Copperplate Gothic Light\")\n",
    "        font.setPointSize(12)\n",
    "        self.sentence1.setFont(font)\n",
    "        self.sentence1.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))\n",
    "        self.sentence1.setAutoFillBackground(True)\n",
    "        self.sentence1.setObjectName(\"sentence1\")\n",
    "        self.label = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.label.setGeometry(QtCore.QRect(0, 460, 801, 31))\n",
    "        palette = QtGui.QPalette()\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(51, 200, 151))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(110, 255, 208))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(80, 227, 179))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(25, 100, 75))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(34, 133, 101))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(51, 200, 151))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(153, 227, 203))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(51, 200, 151))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(110, 255, 208))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(80, 227, 179))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(25, 100, 75))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(34, 133, 101))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(51, 200, 151))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(153, 227, 203))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(25, 100, 75))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(51, 200, 151))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(110, 255, 208))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(80, 227, 179))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(25, 100, 75))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(34, 133, 101))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(25, 100, 75))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(25, 100, 75))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(51, 200, 151))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(51, 200, 151))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(51, 200, 151))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)\n",
    "        self.label.setPalette(palette)\n",
    "        font = QtGui.QFont()\n",
    "        font.setFamily(\"Arial\")\n",
    "        self.label.setFont(font)\n",
    "        self.label.setAutoFillBackground(True)\n",
    "        self.label.setObjectName(\"label\")\n",
    "        self.ac2 = QtWidgets.QPushButton(self.centralwidget)\n",
    "        self.ac2.setGeometry(QtCore.QRect(200, 540, 71, 23))\n",
    "        font = QtGui.QFont()\n",
    "        font.setFamily(\"Rockwell\")\n",
    "        font.setPointSize(10)\n",
    "        self.ac2.setFont(font)\n",
    "        self.ac2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))\n",
    "        self.ac2.setText(\"\")\n",
    "        self.ac2.setObjectName(\"ac2\")\n",
    "        self.ac1 = QtWidgets.QPushButton(self.centralwidget)\n",
    "        self.ac1.setGeometry(QtCore.QRect(80, 500, 75, 23))\n",
    "        font = QtGui.QFont()\n",
    "        font.setFamily(\"Rockwell\")\n",
    "        font.setPointSize(10)\n",
    "        font.setBold(False)\n",
    "        font.setItalic(False)\n",
    "        font.setUnderline(False)\n",
    "        font.setWeight(50)\n",
    "        font.setStrikeOut(False)\n",
    "        self.ac1.setFont(font)\n",
    "        self.ac1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))\n",
    "        self.ac1.setText(\"\")\n",
    "        self.ac1.setObjectName(\"ac1\")\n",
    "        self.ac3 = QtWidgets.QPushButton(self.centralwidget)\n",
    "        self.ac3.setGeometry(QtCore.QRect(340, 500, 75, 23))\n",
    "        font = QtGui.QFont()\n",
    "        font.setFamily(\"Rockwell\")\n",
    "        font.setPointSize(10)\n",
    "        self.ac3.setFont(font)\n",
    "        self.ac3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))\n",
    "        self.ac3.setText(\"\")\n",
    "        self.ac3.setObjectName(\"ac3\")\n",
    "        self.ac4 = QtWidgets.QPushButton(self.centralwidget)\n",
    "        self.ac4.setGeometry(QtCore.QRect(560, 500, 75, 23))\n",
    "        font = QtGui.QFont()\n",
    "        font.setFamily(\"Rockwell\")\n",
    "        font.setPointSize(10)\n",
    "        self.ac4.setFont(font)\n",
    "        self.ac4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))\n",
    "        self.ac4.setText(\"\")\n",
    "        self.ac4.setAutoDefault(False)\n",
    "        self.ac4.setDefault(False)\n",
    "        self.ac4.setObjectName(\"ac4\")\n",
    "        self.ac5 = QtWidgets.QPushButton(self.centralwidget)\n",
    "        self.ac5.setGeometry(QtCore.QRect(450, 540, 75, 23))\n",
    "        font = QtGui.QFont()\n",
    "        font.setFamily(\"Rockwell\")\n",
    "        font.setPointSize(10)\n",
    "        self.ac5.setFont(font)\n",
    "        self.ac5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))\n",
    "        self.ac5.setText(\"\")\n",
    "        self.ac5.setObjectName(\"ac5\")\n",
    "        self.Predict = QtWidgets.QPushButton(self.centralwidget)\n",
    "        self.Predict.setGeometry(QtCore.QRect(550, 370, 81, 21))\n",
    "        self.Predict.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))\n",
    "        self.Predict.setObjectName(\"Predict\")\n",
    "        self.del_word = QtWidgets.QPushButton(self.centralwidget)\n",
    "        self.del_word.setGeometry(QtCore.QRect(710, 500, 75, 23))\n",
    "        self.del_word.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))\n",
    "        self.del_word.setObjectName(\"del_word\")\n",
    "        self.del_sentence = QtWidgets.QPushButton(self.centralwidget)\n",
    "        self.del_sentence.setGeometry(QtCore.QRect(710, 550, 75, 23))\n",
    "        self.del_sentence.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))\n",
    "        self.del_sentence.setObjectName(\"del_sentence\")\n",
    "        self.sound = QtWidgets.QPushButton(self.centralwidget)\n",
    "        self.sound.setGeometry(QtCore.QRect(730, 410, 41, 31))\n",
    "        self.sound.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))\n",
    "        self.sound.setAutoFillBackground(True)\n",
    "        self.sound.setText(\"\")\n",
    "        icon = QtGui.QIcon()\n",
    "        icon.addPixmap(QtGui.QPixmap(\"sound.png\"), QtGui.QIcon.Normal, QtGui.QIcon.Off)\n",
    "        self.sound.setIcon(icon)\n",
    "        self.sound.setIconSize(QtCore.QSize(50, 40))\n",
    "        self.sound.setAutoDefault(False)\n",
    "        self.sound.setDefault(True)\n",
    "        self.sound.setFlat(False)\n",
    "        self.sound.setObjectName(\"sound\")\n",
    "        self.video = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.video.setGeometry(QtCore.QRect(20, 80, 341, 251))\n",
    "        self.video.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))\n",
    "        self.video.setAutoFillBackground(True)\n",
    "        self.video.setText(\"\")\n",
    "        self.video.setScaledContents(True)\n",
    "        self.video.setObjectName(\"video\")\n",
    "        self.b1 = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.b1.setGeometry(QtCore.QRect(-10, 40, 21, 551))\n",
    "        palette = QtGui.QPalette()\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(142, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(117, 214, 214))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(62, 115, 115))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(174, 214, 214))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(142, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(117, 214, 214))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(62, 115, 115))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(174, 214, 214))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(142, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(117, 214, 214))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(62, 115, 115))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)\n",
    "        self.b1.setPalette(palette)\n",
    "        self.b1.setAutoFillBackground(True)\n",
    "        self.b1.setText(\"\")\n",
    "        self.b1.setScaledContents(False)\n",
    "        self.b1.setObjectName(\"b1\")\n",
    "        self.b1_2 = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.b1_2.setGeometry(QtCore.QRect(790, 40, 31, 571))\n",
    "        palette = QtGui.QPalette()\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(142, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(117, 214, 214))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(62, 115, 115))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(174, 214, 214))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(142, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(117, 214, 214))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(62, 115, 115))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(174, 214, 214))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(142, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(117, 214, 214))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(62, 115, 115))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(46, 86, 86))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(93, 173, 173))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)\n",
    "        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))\n",
    "        brush.setStyle(QtCore.Qt.SolidPattern)\n",
    "        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)\n",
    "        self.b1_2.setPalette(palette)\n",
    "        self.b1_2.setAutoFillBackground(True)\n",
    "        self.b1_2.setText(\"\")\n",
    "        self.b1_2.setScaledContents(False)\n",
    "        self.b1_2.setObjectName(\"b1_2\")\n",
    "        MainWindow.setCentralWidget(self.centralwidget)\n",
    "        self.menubar = QtWidgets.QMenuBar(MainWindow)\n",
    "        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))\n",
    "        self.menubar.setObjectName(\"menubar\")\n",
    "        self.menuAbout = QtWidgets.QMenu(self.menubar)\n",
    "        self.menuAbout.setObjectName(\"menuAbout\")\n",
    "        MainWindow.setMenuBar(self.menubar)\n",
    "        self.statusbar = QtWidgets.QStatusBar(MainWindow)\n",
    "        self.statusbar.setObjectName(\"statusbar\")\n",
    "        MainWindow.setStatusBar(self.statusbar)\n",
    "\n",
    "        self.info = QtWidgets.QAction(MainWindow)\n",
    "        self.info.setShortcut('Ctrl+A')\n",
    "        self.info.setStatusTip('Information about Developer')\n",
    "        self.info.setMenuRole(QtWidgets.QAction.AboutRole)\n",
    "        self.info.triggered.connect(qApp.activePopupWidget)\n",
    "        self.info.setObjectName(\"info\")\n",
    "\n",
    "        self.menuAbout.addAction(self.info)\n",
    "        self.menuAbout.addSeparator()\n",
    "\n",
    "        self.exitAct = QtWidgets.QAction(MainWindow)\n",
    "        self.exitAct.setShortcut('Ctrl+Q')\n",
    "        self.exitAct.setStatusTip('Exit application')\n",
    "        self.exitAct.triggered.connect(qApp.quit)\n",
    "        self.menuAbout.addAction(self.exitAct)\n",
    "        self.menubar.addAction(self.menuAbout.menuAction())\n",
    "\n",
    "        self.retranslateUi(MainWindow)\n",
    "\n",
    "        self.timer = QTimer()\n",
    "        # set timer timeout callback function\n",
    "        self.timer.timeout.connect(self.video_loop)\n",
    "        self.Predict.clicked.connect(self.controlTimer)\n",
    "        self.del_word.clicked.connect(self.delw)\n",
    "        self.del_sentence.clicked.connect(self.delet)\n",
    "        self.sound.clicked.connect(self.speak)\n",
    "\n",
    "        self.ac1.clicked.connect(self.action1)\n",
    "        self.ac3.clicked.connect(self.action2)\n",
    "        self.ac4.clicked.connect(self.action3)\n",
    "        self.ac2.clicked.connect(self.action4)\n",
    "        self.ac5.clicked.connect(self.action5)\n",
    "\n",
    "\n",
    "        self.hs = enchant.Dict(\"en_US\")\n",
    "        # self.vs = cv2.VideoCapture(0)\n",
    "        self.ct = {}\n",
    "        self.ct['blank'] = 0\n",
    "        self.blank_flag = 0\n",
    "        for i in ascii_uppercase:\n",
    "            self.ct[i] = 0\n",
    "\n",
    "        self.str = \"\"\n",
    "        self.word = \"\"\n",
    "        self.current_symbol = \"Empty\"\n",
    "\n",
    "        self.model = tf.models.load_model('keras_model_main.h5', compile=False)\n",
    "        self.model_dru = tf.models.load_model('keras_model_dru.h5', compile=False)\n",
    "        self.model_mns = tf.models.load_model('keras_model_mns.h5', compile=False)\n",
    "        self.model_dikr = tf.models.load_model('keras_model_dikr.h5', compile=False)\n",
    "        self.model_kvw = tf.models.load_model('keras_model_kvw.h5', compile=False)\n",
    "\n",
    "        print(\"Loaded model from disk\")\n",
    "\n",
    "        QtCore.QMetaObject.connectSlotsByName(MainWindow)\n",
    "\n",
    "\n",
    "\n",
    "    def retranslateUi(self, MainWindow):\n",
    "        _translate = QtCore.QCoreApplication.translate\n",
    "        MainWindow.setWindowTitle(_translate(\"MainWindow\", \"Sign To Text\"))\n",
    "        self.Heading.setText(_translate(\"MainWindow\", \"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 4.0//EN\\\" \\\"http://www.w3.org/TR/REC-html40/strict.dtd\\\">\\n\"\n",
    "\"<html><head><meta name=\\\"qrichtext\\\" content=\\\"1\\\" /><style type=\\\"text/css\\\">\\n\"\n",
    "\"p, li { white-space: pre-wrap; }\\n\"\n",
    "\"</style></head><body style=\\\" font-family:\\'Baskerville Old Face\\'; font-size:8pt; font-weight:400; font-style:normal;\\\">\\n\"\n",
    "\"<p align=\\\"center\\\" style=\\\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\\\"><span style=\\\" font-size:24pt; color:#ffffff;\\\">Sign To Text</span></p></body></html>\"))\n",
    "        self.character.setText(_translate(\"MainWindow\", \"<html><head/><body><p align=\\\"center\\\"><span style=\\\" font-size:14pt;\\\">Character  :</span></p></body></html>\"))\n",
    "        self.word.setText(_translate(\"MainWindow\", \"<html><head/><body><p align=\\\"center\\\"><span style=\\\" font-size:14pt;\\\">Word :</span></p></body></html>\"))\n",
    "        self.sentence.setText(_translate(\"MainWindow\", \"<html><head/><body><p align=\\\"center\\\"><span style=\\\" font-size:14pt;\\\">Sentence :</span></p><p align=\\\"center\\\"><br/></p></body></html>\"))\n",
    "        self.ch.setText(_translate(\"MainWindow\", \"<html><head/><body><p align=\\\"center\\\"><span style=\\\" font-size:12pt;\\\"><br/></span></p></body></html>\"))\n",
    "        self.word1.setText(_translate(\"MainWindow\", \"<html><head/><body><p align=\\\"center\\\"><span style=\\\" font-size:12pt;\\\"><br/></span></p></body></html>\"))\n",
    "        self.sentence1.setText(_translate(\"MainWindow\", \"<html><head/><body><p align=\\\"center\\\"><span style=\\\" font-size:12pt;\\\"><br/></span></p></body></html>\"))\n",
    "        self.label.setText(_translate(\"MainWindow\", \"<html><head/><body><p align=\\\"center\\\"><span style=\\\" font-size:14pt; color:#ffffff;\\\">Suggestions</span></p></body></html>\"))\n",
    "        self.Predict.setText(_translate(\"MainWindow\", \"Predict\"))\n",
    "        self.del_word.setText(_translate(\"MainWindow\", \"DEL Word\"))\n",
    "        self.del_sentence.setText(_translate(\"MainWindow\", \"DEL Sentence\"))\n",
    "        self.menuAbout.setTitle(_translate(\"MainWindow\", \"About\"))\n",
    "        self.info.setText(_translate(\"MainWindow\", \"Info\"))\n",
    "        self.exitAct.setText(_translate(\"MainWindow\", \"Quit\"))\n",
    "\n",
    "\n",
    "    def controlTimer(self):\n",
    "        # if timer is stopped\n",
    "        if not self.timer.isActive():\n",
    "            # create video capture\n",
    "            self.vs = cv2.VideoCapture(0)\n",
    "            # start timer\n",
    "            self.timer.start(20)\n",
    "            # update control_bt text\n",
    "            self.Predict.setText(\"Stop\")\n",
    "        # if timer is started\n",
    "        else:\n",
    "            # stop timer\n",
    "            self.timer.stop()\n",
    "            # release video capture\n",
    "            self.vs.release()\n",
    "            # update control_bt text\n",
    "            self.Predict.setText(\"Start\")\n",
    "\n",
    "    def video_loop(self):\n",
    "        ok, frame = self.vs.read()\n",
    "        if ok:\n",
    "\n",
    "            np.set_printoptions(suppress=True)\n",
    "            data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)\n",
    "            frame = cv2.flip(frame, 1)\n",
    "            x1 = int(0.5 * frame.shape[1])\n",
    "            y1 = 10\n",
    "            x2 = frame.shape[1] - 10\n",
    "            y2 = int(0.5 * frame.shape[1])\n",
    "            square_frame = frame[y1:y2, x1:x2]\n",
    "            resized_img = cv2.resize(square_frame, (224, 224))\n",
    "            model_img = cv2.cvtColor(resized_img, cv2.COLOR_BGR2RGB)\n",
    "            image_array = np.asarray(model_img)\n",
    "            normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1\n",
    "            data[0] = normalized_image_array\n",
    "\n",
    "            # image _ on gui\n",
    "            height, width, channel = model_img.shape\n",
    "            step = channel * width\n",
    "            # create QImage from RGB frame\n",
    "            qImg = QImage(model_img.data, width, height, step, QImage.Format_RGB888)\n",
    "            # show image in img_label\n",
    "            # self.Img.setPixmap(QtGui.QPixmap(\"signs.png\"))\n",
    "\n",
    "            self.video.setPixmap(QPixmap.fromImage(qImg))\n",
    "\n",
    "            # self.ui.image_label.setPixmap(QPixmap.fromImage(qImg))\n",
    "\n",
    "            self.predict(data)\n",
    "\n",
    "            self.ch.setText(self.current_symbol)\n",
    "            self.word1.setText(self.word)\n",
    "            self.sentence1.setText(self.str)\n",
    "\n",
    "            if self.word:\n",
    "                self.hs.check(self.word)\n",
    "                predicts = self.hs.suggest(self.word)\n",
    "                if (len(predicts) > 0):\n",
    "                    self.ac1.setText(predicts[0])\n",
    "                else:\n",
    "                    self.ac1.setText(\"\")\n",
    "                if (len(predicts) > 1):\n",
    "                    self.ac3.setText(predicts[1])\n",
    "                else:\n",
    "                    self.ac3.setText(\"\")\n",
    "                if (len(predicts) > 2):\n",
    "                    self.ac4.setText(predicts[2])\n",
    "                else:\n",
    "                    self.ac4.setText(\"\")\n",
    "                if (len(predicts) > 3):\n",
    "                    self.ac2.setText(predicts[3])\n",
    "                else:\n",
    "                    self.ac2.setText(\"\")\n",
    "                if (len(predicts) > 0):\n",
    "                    self.ac5.setText(self.word)\n",
    "                else:\n",
    "                    self.ac5.setText(\"\")\n",
    "\n",
    "    def predict(self, test_image):\n",
    "        # test_image = cv2.resize(test_image, (128, 128))\n",
    "\n",
    "        result = self.model.predict(test_image)\n",
    "        result_dru = self.model_dru.predict(test_image)\n",
    "        result_tkdi = self.model_dikr.predict(test_image)\n",
    "        result_smn = self.model_mns.predict(test_image)\n",
    "        result_kvw = self.model_kvw.predict(test_image)\n",
    "        prediction = {}\n",
    "        prediction['blank'] = result[0][0]\n",
    "        inde = 1\n",
    "        for i in ascii_uppercase:\n",
    "            prediction[i] = result[0][inde]\n",
    "            inde += 1\n",
    "        # LAYER 1\n",
    "        prediction = sorted(prediction.items(), key=operator.itemgetter(1), reverse=True)\n",
    "        self.current_symbol = prediction[0][0]\n",
    "        # LAYER 2\n",
    "        if (self.current_symbol == 'D' or self.current_symbol == 'R' or self.current_symbol == 'U'):\n",
    "            prediction = {}\n",
    "            prediction['D'] = result_dru[0][0]\n",
    "            prediction['R'] = result_dru[0][1]\n",
    "            prediction['U'] = result_dru[0][2]\n",
    "            prediction = sorted(prediction.items(), key=operator.itemgetter(1), reverse=True)\n",
    "            self.current_symbol = prediction[0][0]\n",
    "\n",
    "        if (\n",
    "                self.current_symbol == 'D' or self.current_symbol == 'I' or self.current_symbol == 'K' or self.current_symbol == 'R'):\n",
    "            prediction = {}\n",
    "            prediction['D'] = result_tkdi[0][0]\n",
    "            prediction['I'] = result_tkdi[0][1]\n",
    "            prediction['K'] = result_tkdi[0][2]\n",
    "            prediction['R'] = result_tkdi[0][3]\n",
    "            prediction = sorted(prediction.items(), key=operator.itemgetter(1), reverse=True)\n",
    "            self.current_symbol = prediction[0][0]\n",
    "\n",
    "        if (self.current_symbol == 'M' or self.current_symbol == 'N' or self.current_symbol == 'S'):\n",
    "            prediction = {}\n",
    "            prediction['M'] = result_smn[0][0]\n",
    "            prediction['N'] = result_smn[0][1]\n",
    "            prediction['S'] = result_smn[0][2]\n",
    "            prediction = sorted(prediction.items(), key=operator.itemgetter(1), reverse=True)\n",
    "\n",
    "            self.current_symbol = prediction[0][0]\n",
    "\n",
    "        if (self.current_symbol == 'K' or self.current_symbol == 'V' or self.current_symbol == 'W'):\n",
    "            prediction = {}\n",
    "            prediction['K'] = result_kvw[0][0]\n",
    "            prediction['V'] = result_kvw[0][1]\n",
    "            prediction['W'] = result_kvw[0][2]\n",
    "            prediction = sorted(prediction.items(), key=operator.itemgetter(1), reverse=True)\n",
    "\n",
    "            self.current_symbol = prediction[0][0]\n",
    "\n",
    "        if (self.current_symbol == 'blank'):\n",
    "            for i in ascii_uppercase:\n",
    "                self.ct[i] = 0\n",
    "        self.ct[self.current_symbol] += 1\n",
    "        if (self.ct[self.current_symbol] > 10):\n",
    "            for i in ascii_uppercase:\n",
    "                if i == self.current_symbol:\n",
    "                    continue\n",
    "                tmp = self.ct[self.current_symbol] - self.ct[i]\n",
    "                if tmp < 0:\n",
    "                    tmp *= -1\n",
    "                if tmp <= 3:\n",
    "                    self.ct['blank'] = 0\n",
    "                    for i in ascii_uppercase:\n",
    "                        self.ct[i] = 0\n",
    "                    return\n",
    "            self.ct['blank'] = 0\n",
    "            for i in ascii_uppercase:\n",
    "                self.ct[i] = 0\n",
    "            if self.current_symbol == 'blank':\n",
    "                if self.blank_flag == 0:\n",
    "                    self.blank_flag = 1\n",
    "                    if len(self.str) > 0:\n",
    "                        self.str += \" \"\n",
    "                    self.str += self.word\n",
    "                    self.word = \"\"\n",
    "            else:\n",
    "                if (len(self.str) > 24):\n",
    "                    self.str = \"\"\n",
    "                self.blank_flag = 0\n",
    "                self.word += self.current_symbol\n",
    "\n",
    "    def action1(self):\n",
    "        self.hs.check(self.word)\n",
    "        predicts = self.hs.suggest(self.word)\n",
    "        if (len(predicts) > 0):\n",
    "            self.word = \"\"\n",
    "            self.str += \" \"\n",
    "            self.str += predicts[0]\n",
    "\n",
    "    def action2(self):\n",
    "        self.hs.check(self.word)\n",
    "        predicts = self.hs.suggest(self.word)\n",
    "        if (len(predicts) > 1):\n",
    "            self.word = \"\"\n",
    "            self.str += \" \"\n",
    "            self.str += predicts[1]\n",
    "\n",
    "    def action3(self):\n",
    "        self.hs.check(self.word)\n",
    "        predicts = self.hs.suggest(self.word)\n",
    "        if (len(predicts) > 2):\n",
    "            self.word = \"\"\n",
    "            self.str += \" \"\n",
    "            self.str += predicts[2]\n",
    "\n",
    "    def action4(self):\n",
    "        self.hs.check(self.word)\n",
    "        predicts = self.hs.suggest(self.word)\n",
    "        if (len(predicts) > 3):\n",
    "            self.word = \"\"\n",
    "            self.str += \" \"\n",
    "            self.str += predicts[3]\n",
    "\n",
    "    def destructor(self):\n",
    "        print(\"Closing Application...\")\n",
    "        root.destroy()\n",
    "        self.vs.release()\n",
    "        cv2.destroyAllWindows()\n",
    "\n",
    "    def action5(self):\n",
    "        self.str += \" \"\n",
    "        self.str += self.word\n",
    "        self.word = \"\"\n",
    "\n",
    "    def delet(self):\n",
    "        self.str = self.str.split()[:-1]\n",
    "        self.str = ' '.join(self.str)\n",
    "\n",
    "    def delw(self):\n",
    "        self.word = self.word[:-1]\n",
    "\n",
    "    def speak(self):\n",
    "        try:\n",
    "            engine.say(self.str)\n",
    "            engine.runAndWait()\n",
    "        except:\n",
    "            print('No Word')\n",
    "\n",
    "\n",
    "\n",
    "    print(\"Starting Application...\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    import sys\n",
    "    app = QtWidgets.QApplication(sys.argv)\n",
    "    MainWindow = QtWidgets.QMainWindow()\n",
    "    ui = Ui_MainWindow()\n",
    "    ui.setupUi(MainWindow)\n",
    "    loader()\n",
    "    MainWindow.show()\n",
    "    #ui.vs.release()\n",
    "    sys.exit(app.exec_())\n",
    "def predictions():\n",
    "    #The prediction model code goes here\n",
    "    #Once the start Button is pressed the prediction model starts\n",
    "    pass\n",
    "@app.route('/stop',methods=['POST','GET'])\n",
    "def stopping():\n",
    "    #The text to speech code goes here\n",
    "    #Once the stop button is pressed the text is converted into speech\n",
    "    pass\n",
    "\n",
    "@app.route('/video')\n",
    "def video():\n",
    "    return Response(generate_frames(),mimetype='multipart/x-mixed-replace; boundary=frame')\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "\tapp.run(debug=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
